In [43]:
import numpy as np
import pandas as pd

In [44]:
#importing dataset


In [45]:
dataset=pd.read_csv("weatherAUS.csv")
print(dataset.iloc[:,[2,4,7,8,13]])
X=dataset.iloc[:,[2,4,7,8,13]].values
Y=dataset.iloc[:,-1].values
print(X)
print(Y)


        MinTemp  Rainfall WindGustDir  WindGustSpeed  Humidity9am
0          13.4       0.6           W           44.0         71.0
1           7.4       0.0         WNW           44.0         44.0
2          12.9       0.0         WSW           46.0         38.0
3           9.2       0.0          NE           24.0         45.0
4          17.5       1.0           W           41.0         82.0
...         ...       ...         ...            ...          ...
145455      2.8       0.0           E           31.0         51.0
145456      3.6       0.0         NNW           22.0         56.0
145457      5.4       0.0           N           37.0         53.0
145458      7.8       0.0          SE           28.0         51.0
145459     14.9       0.0         NaN            NaN         62.0

[145460 rows x 5 columns]
[[13.4 0.6 'W' 44.0 71.0]
 [7.4 0.0 'WNW' 44.0 44.0]
 [12.9 0.0 'WSW' 46.0 38.0]
 ...
 [5.4 0.0 'N' 37.0 53.0]
 [7.8 0.0 'SE' 28.0 51.0]
 [14.9 0.0 nan nan 62.0]]
['No' 'No' 'No' ..

In [46]:
Y=Y.reshape(-1,1)
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
X=imputer.fit_transform(X)
Y=imputer.fit_transform(Y)



In [47]:
#Encode to integer
from sklearn.preprocessing import LabelEncoder
le_1=LabelEncoder()
X[:,2]=le_1.fit_transform(X[:,2])
le_2=LabelEncoder()
Y=le_2.fit_transform(Y)

C:\Users\najee\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [48]:
print(X)

[[13.4 0.6 13 44.0 71.0]
 [7.4 0.0 14 44.0 44.0]
 [12.9 0.0 15 46.0 38.0]
 ...
 [5.4 0.0 3 37.0 53.0]
 [7.8 0.0 9 28.0 51.0]
 [14.9 0.0 13 35.0 62.0]]


In [49]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)


In [50]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)


In [51]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=100,random_state=0)
classifier.fit(X_train,Y_train)


RandomForestClassifier(random_state=0)

In [52]:
classifier.score(X_train,Y_train)


0.9958923415371923

In [56]:
print(classifier.predict_proba(X_test)[9])

[0.95 0.05]
